# Generated by Django 3.2.7 on 2021-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=30)),
                ('month_birth', models.CharField(max_length=15)),
                ('date_birth', models.CharField(max_length=2)),
                ('year_birth', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=25)),
                ('date_registered', models.DateField(max_length=15)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
